import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
	{
		id: "101",
		firstName: "Nitin",
		lastName: "Kalra",
		username: "heynitin",
		password: "justfortest",
		following: [
			{
				username: "naval",
				id: "102",
				firstName: "Naval",
				lastName: "Ravikant",
				profilePicture: "https://i.postimg.cc/RCDBg33G/profile-Naval.jpg",
			},
			{
				username: "jalebifafda",
				firstName: "Jethalal",
				lastName: "Gada",
				id: "106",
				profilePicture: "https://i.postimg.cc/bJGsB7RB/profile-Jhetha.jpg",
			},
		],
		followers: [
			{
				username: "naval",
				id: "102",
				firstName: "Naval",
				lastName: "Ravikant",
				profilePicture: "https://i.postimg.cc/RCDBg33G/profile-Naval.jpg",
			},
			{
				username: "kunalb11",
				id: "103",
				firstName: "Kunal",
				lastName: "Shah",
				profilePicture: "https://i.postimg.cc/K8VfV2P6/profile-Kunal.jpg",
			},
			{
				username: "cayahere",
				id: "104",
				firstName: "Jose",
				lastName: "Cayasso",
				profilePicture: "https://i.postimg.cc/rFsSLHwM/profile-caya.jpg",
			},
		],
		bookmarks: [],
		profilePicture: "https://i.postimg.cc/6p1n3fTn/profile-Nitin.jpg",
		bio: "I'm a front-end developer with ReactJs as my sword.",
		website: "https://github.com/HeyNitin",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: "102",
		firstName: "Naval",
		lastName: "Ravikant",
		username: "naval",
		password: "creativejobs",
		following: [
			{
				username: "heynitin",
				id: "101",
				firstName: "Nitin",
				lastName: "Kalra",
				profilePicture: "https://i.postimg.cc/6p1n3fTn/profile-Nitin.jpg",
			},
			{
				username: "cayahere",
				id: "104",
				firstName: "Jose",
				lastName: "Cayasso",
				profilePicture: "https://i.postimg.cc/rFsSLHwM/profile-caya.jpg",
			},
		],
		followers: [
			{
				username: "heynitin",
				id: "101",
				firstName: "Nitin",
				lastName: "Kalra",
				profilePicture: "https://i.postimg.cc/6p1n3fTn/profile-Nitin.jpg",
			},
		],
		profilePicture: "https://i.postimg.cc/RCDBg33G/profile-Naval.jpg",
		bio: "",
		website: "",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: "103",
		firstName: "Kunal",
		lastName: "Shah",
		username: "kunalb11",
		password: "realityisamyth",
		following: [
			{
				username: "heynitin",
				id: "101",
				firstName: "Nitin",
				lastName: "Kalra",
				profilePicture: "https://i.postimg.cc/6p1n3fTn/profile-Nitin.jpg",
			},
			{
				username: "cayahere",
				id: "104",
				firstName: "Jose",
				lastName: "Cayasso",
				profilePicture: "https://i.postimg.cc/rFsSLHwM/profile-caya.jpg",
			},
		],
		followers: [],
		profilePicture: "https://i.postimg.cc/K8VfV2P6/profile-Kunal.jpg",
		bio: "",
		website: "",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: "104",
		firstName: "Jose",
		lastName: "Cayasso",
		username: "cayahere",
		password: "slidebeanforthewin",
		following: [
			{
				username: "heynitin",
				id: "101",
				firstName: "Nitin",
				lastName: "Kalra",
				profilePicture: "https://i.postimg.cc/6p1n3fTn/profile-Nitin.jpg",
			},
		],
		followers: [
			{
				username: "naval",
				id: "102",
				firstName: "Naval",
				lastName: "Ravikant",
				profilePicture: "https://i.postimg.cc/RCDBg33G/profile-Naval.jpg",
			},
			{
				username: "kunalb11",
				id: "103",
				firstName: "Kunal",
				lastName: "Shah",
				profilePicture: "https://i.postimg.cc/RCDBg33G/profile-Naval.jpg",
			},
		],
		profilePicture: "https://i.postimg.cc/rFsSLHwM/profile-caya.jpg",
		bio: "",
		website: "",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: "105",
		firstName: "John",
		lastName: "Cena",
		username: "youcantreadthis",
		password: "youcanttypethis",
		following: [],
		followers: [],
		profilePicture: "https://i.postimg.cc/3xMWbfyL/profile-John.jpg",
		bio: "",
		website: "",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: "106",
		firstName: "Jethalal",
		lastName: "Gada",
		username: "jalebifafda",
		password: "chaipiyobiscuitkhao",
		following: [],
		followers: [
			{
				username: "heynitin",
				id: "101",
				firstName: "Nitin",
				lastName: "Kalra",
				profilePicture: "https://i.postimg.cc/6p1n3fTn/profile-Nitin.jpg",
			},
		],
		profilePicture: "https://i.postimg.cc/bJGsB7RB/profile-Jhetha.jpg",
		bio: "",
		website: "",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: "107",
		firstName: "Nobita",
		lastName: "Nobi",
		username: "doremonadmirer",
		password: "givemegadget",
		following: [],
		followers: [],
		profilePicture: "https://i.postimg.cc/brW050bQ/profile-Nobita.jpg",
		bio: "",
		website: "",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: "108",
		firstName: "Doremon",
		lastName: "The Robot",
		username: "doremon",
		password: "nobitasgod",
		following: [],
		followers: [],
		profilePicture: "https://i.postimg.cc/DzX9p5Xc/profile-Doremon.jpg",
		bio: "",
		website: "",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
];
